FROM python:3.12-slim
WORKDIR /app
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir --no-compile -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt \
    && rm -rf /root/.cache/pip /tmp/*
COPY backend/ ./
COPY frontend/dist ./static
RUN rm -rf __pycache__ data
ENV PYTHONUNBUFFERED=1
ENV STATIC_FOLDER=/app/static
EXPOSE 5001
CMD ["python", "app.py"]
