/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgeGauge: typeof import('./components/inventory/time/AgeGauge.vue')['default']
    AgePyramid: typeof import('./components/inventory/time/AgePyramid.vue')['default']
    AgeStructureChart: typeof import('./components/charts/AgeStructureChart.vue')['default']
    AgeTrend: typeof import('./components/inventory/time/AgeTrend.vue')['default']
    AnomalyCalendar: typeof import('./components/inventory/claim/AnomalyCalendar.vue')['default']
    BatchProgress: typeof import('./components/inventory/structure/BatchProgress.vue')['default']
    BuyerRanking: typeof import('./components/inventory/structure/BuyerRanking.vue')['default']
    CategoryBubble: typeof import('./components/inventory/structure/CategoryBubble.vue')['default']
    ChartCard: typeof import('./components/common/ChartCard.vue')['default']
    ClaimGauge: typeof import('./components/charts/ClaimGauge.vue')['default']
    CleanupProgress: typeof import('./components/inventory/actions/CleanupProgress.vue')['default']
    CrossBarChart: typeof import('./components/inventory/cross/CrossBarChart.vue')['default']
    CrossLineChart: typeof import('./components/inventory/cross/CrossLineChart.vue')['default']
    CrossPieChart: typeof import('./components/inventory/cross/CrossPieChart.vue')['default']
    DataDetail: typeof import('./components/inventory/DataDetail.vue')['default']
    DimensionPanel: typeof import('./components/tables/DimensionPanel.vue')['default']
    DonutChart: typeof import('./components/charts/DonutChart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ErrorResult: typeof import('./components/common/ErrorResult.vue')['default']
    InboundOutboundCompare: typeof import('./components/inventory/claim/InboundOutboundCompare.vue')['default']
    KpiCards: typeof import('./components/inventory/KpiCards.vue')['default']
    KpiOverview: typeof import('./components/kpi/KpiOverview.vue')['default']
    OptimizeSuggest: typeof import('./components/inventory/actions/OptimizeSuggest.vue')['default']
    OverstockChart: typeof import('./components/inventory/actions/OverstockChart.vue')['default']
    ProjectHeatmap: typeof import('./components/inventory/cross/ProjectHeatmap.vue')['default']
    ProjectTreemap: typeof import('./components/inventory/structure/ProjectTreemap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenAdapter: typeof import('./components/common/ScreenAdapter.vue')['default']
    SectionHeader: typeof import('./components/inventory/SectionHeader.vue')['default']
    SluggishHeatmap: typeof import('./components/inventory/time/SluggishHeatmap.vue')['default']
    SluggishTable: typeof import('./components/inventory/actions/SluggishTable.vue')['default']
    TopRankings: typeof import('./components/tables/TopRankings.vue')['default']
    UsageRateTrend: typeof import('./components/inventory/claim/UsageRateTrend.vue')['default']
    WaterLevelChart: typeof import('./components/inventory/claim/WaterLevelChart.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
